openapi: 3.0.3
info:
  title: Warehouse API
  description: Warehouse API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /products:
    get:
      summary: Get all products
      parameters:
        - name: pageSize
          in: query
        - name: offset
          in: query
      responses:
        "200":
          description: "Products page read"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        stock:
          type: integer
    Product:
      type: object
      properties:
        name:
          type: string
        contain_articles:
          type: array
          items:
            $ref: '#/components/schemas/Article'



