version: '3'
services:
  app:
    build: ../
    container_name: warehouse_app
    restart: always
    depends_on:
      - api
    ports:
      - '3000:3000'
  api:
    build: ../api/
    container_name: warehouse_api
    restart: always
    depends_on:
     - db
    ports:
      - '8080:8080'
    environment:
      MONGO_URI: mongodb://warehouse_db:27017/warehouse-react
  db:
    image: mongo:latest
    container_name: warehouse_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/mongo:/data/db
volumes:
  mongodb:

