openapi: 3.0.3
info:
  title: Warehouse API
  description: Warehouse API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /product:
    get:
      summary: Get all products
      tags:
        - Products
      parameters:
        - name: page_size
          in: query
          schema:
            type: number
            minimum: 1
          example: 10
        - name: offset
          in: query
          schema:
            type: number
            minimum: 0
          example: 0
      responses:
        '200':
          description: Products page read
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductAvailable'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Import products
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
      responses:
        '201':
          description: Products saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Sell product
      tags:
        - Products
      parameters:
        - name: name
          in: query
          required: true
        - name: amount
          in: query
          required: true
          schema:
            type: number
            minimum: 1
      responses:
        '200':
          description: Inventory updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid sell parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Product not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /inventory:
    post:
      summary: Import inventory
      tags:
        - Inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
      responses:
        '201':
          description: Inventory saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Article:
      type: object
      properties:
        art_id:
          type: string
          example: '1'
        name:
          type: string
          example: 'leg'
        stock:
          type: integer
          example: 1
    Product:
      type: object
      properties:
        name:
          type: string
          example: 'Dinning Table'
        contain_articles:
          type: array
          items:
            type: object
            properties:
              art_id:
                type: string
                example: '1'
              amount_of:
                type: string
                example: '1'
    ProductAvailable:
      type: object
      properties:
        name:
          type: string
          example: 'Dinning Table'
        stock:
          type: number
          example: 2
    Products:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Inventory:
      type: object
      properties:
        inventory:
          type: array
          items:
            $ref: '#/components/schemas/Article'



